SELECT * FROM VENDEDORES;


UPDATE VENDEDORES SET COMISSAO = COMISSAO * 1.1;



BEGIN TRANSACTION 

INSERT INTO VENDEDORES 
VALUES ('239', 'Maria Joana', 'Copacabana', '0.2', '2015-01-01', 1);


ROLLBACK