USE [VENDAS SUCOS]
GO

/****** Object:  Table [dbo].[PRODUTOS]    Script Date: 05/06/2023 10:29:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PRODUTOS_2](
	[CODIGO] [varchar](10) NOT NULL,
	[DESCRITOR] [varchar](100) NULL,
	[SABOR] [varchar](50) NULL,
	[TAMANHO] [varchar](50) NULL,
	[EMBALAGEM] [varchar](50) NULL,
	[PRECO_LISTA] [float] NULL
) ON [PRIMARY]
GO

INSERT INTO PRODUTOS_2 SELECT * FROM PRODUTOS;


SELECT * FROM PRODUTOS_2;


DELETE FROM PRODUTOS_2;