CREATE TABLE TAB_FATURAMENTO (
    DATA_VENDA DATE NULL, 
    TOTAL_VENDA FLOAT
);


SELECT 
    TV.DATA_VENDA, 
    SUM (TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA 
FROM TABELA_DE_VENDAS TV 
INNER JOIN TABELA_DE_ITENS_VENDIDOS TIV 
ON TV.NUMERO = TIV.NUMERO 
GROUP BY TV.DATA_VENDA;

select * from CLIENTES

INSERT INTO TABELA_DE_VENDAS 
VALUES (
    '0101', '2018-05-15', '1471156710', '235', 0.18
);

select * from PRODUTOS


INSERT INTO TABELA_DE_ITENS_VENDIDOS 
VALUES (
    '0101', '1040107', 100, 10
);


INSERT INTO TABELA_DE_VENDAS 
VALUES (
    '0102', '2018-05-15', '1040107', '235', 0.18
);

INSERT INTO TABELA_DE_ITENS_VENDIDOS 
VALUES (
    '0102', '1040107', 100, 10
);



INSERT INTO TAB_FATURAMENTO 
SELECT 
    TV.DATA_VENDA, 
    SUM (TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA 
FROM TABELA_DE_VENDAS TV 
INNER JOIN TABELA_DE_ITENS_VENDIDOS TIV 
ON TV.NUMERO = TIV.NUMERO 
GROUP BY TV.DATA_VENDA;


SELECT * FROM TAB_FATURAMENTO;


DELETE FROM TAB_FATURAMENTO;
INSERT INTO TAB_FATURAMENTO 
SELECT 
    TV.DATA_VENDA, 
    SUM (TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA 
FROM TABELA_DE_VENDAS TV 
INNER JOIN TABELA_DE_ITENS_VENDIDOS TIV 
ON TV.NUMERO = TIV.NUMERO 
GROUP BY TV.DATA_VENDA;

--##############################


SELECT * FROM TAB_FATURAMENTO;


INSERT INTO TABELA_DE_VENDAS 
VALUES (
    '0104', '2018-05-16', '1040107', '235', 0.18);

INSERT INTO TABELA_DE_ITENS_VENDIDOS 
VALUES (
    '0104', '1040107', 100, 10);


	DELETE FROM TAB_FATURAMENTO;
INSERT INTO TAB_FATURAMENTO 
SELECT 
    TV.DATA_VENDA, 
    SUM (TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA 
FROM TABELA_DE_VENDAS TV 
INNER JOIN TABELA_DE_ITENS_VENDIDOS TIV 
ON TV.NUMERO = TIV.NUMERO 
GROUP BY TV.DATA_VENDA;


SELECT * FROM TAB_FATURAMENTO;




CREATE TRIGGER TG_CLIENTES_IDADE
ON [CLIENTES]
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
UPDATE [CLIENTES] SET [IDADE] = 
    DATEDIFF(YEAR, [DATA_NASCIMENTO], GETDATE());
END;