CREATE TRIGGER TG_ITENS_VENDIDOS 
ON [dbo].[TABELA_DE_ITENS_VENDIDOS] 
AFTER INSERT, UPDATE, DELETE 
AS 
BEGIN 
DELETE FROM TAB_FATURAMENTO;

INSERT INTO TAB_FATURAMENTO 
SELECT 
    TV.DATA_VENDA, 
    SUM (TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA 
FROM TABELA_DE_VENDAS TV 
INNER JOIN TABELA_DE_ITENS_VENDIDOS TIV 
ON TV.NUMERO = TIV.NUMERO 
GROUP BY TV.DATA_VENDA;

END;

select * from PRODUTOS

SELECT * FROM TAB_FATURAMENTO;


INSERT INTO TABELA_DE_VENDAS 
VALUES (
    '0105', '2018-05-16', '1040107', '235', 0.18);

INSERT INTO TABELA_DE_ITENS_VENDIDOS 
VALUES (
    '0105', '1000889', 150, 10);



INSERT INTO TABELA_DE_VENDAS 
VALUES (
    '0106', '2018-05-16', '1471156710', '235', 0.18);

INSERT INTO TABELA_DE_ITENS_VENDIDOS 
VALUES (
    '0106', '1000889', 150, 10);


	UPDATE TABELA_DE_ITENS_VENDIDOS SET QUANTIDADE = 200 WHERE NUMERO = '0106';

	DELETE FROM TABELA_DE_ITENS_VENDIDOS WHERE NUMERO = '0106';